
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDOWebServiceSoap", targetNamespace = "http://frontstep.com/IDOWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDOWebServiceSoap {


    /**
     * 
     * @return
     *     returns mypackage.ArrayOfString
     */
    @WebMethod(operationName = "GetConfigurationNames", action = "http://frontstep.com/IDOWebService/GetConfigurationNames")
    @WebResult(name = "GetConfigurationNamesResult", targetNamespace = "http://frontstep.com/IDOWebService")
    @RequestWrapper(localName = "GetConfigurationNames", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.GetConfigurationNames")
    @ResponseWrapper(localName = "GetConfigurationNamesResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.GetConfigurationNamesResponse")
    public ArrayOfString getConfigurationNames();

    /**
     * 
     * @param strConfig
     * @param strPswd
     * @param strUserId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateSessionToken", action = "http://frontstep.com/IDOWebService/CreateSessionToken")
    @WebResult(name = "CreateSessionTokenResult", targetNamespace = "http://frontstep.com/IDOWebService")
    @RequestWrapper(localName = "CreateSessionToken", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.CreateSessionToken")
    @ResponseWrapper(localName = "CreateSessionTokenResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.CreateSessionTokenResponse")
    public String createSessionToken(
        @WebParam(name = "strUserId", targetNamespace = "http://frontstep.com/IDOWebService")
        String strUserId,
        @WebParam(name = "strPswd", targetNamespace = "http://frontstep.com/IDOWebService")
        String strPswd,
        @WebParam(name = "strConfig", targetNamespace = "http://frontstep.com/IDOWebService")
        String strConfig);

    /**
     * 
     * @param iRecordCap
     * @param strFilter
     * @param strPostQueryMethod
     * @param strIDOName
     * @param strSessionToken
     * @param strPropertyList
     * @param strOrderBy
     * @return
     *     returns mypackage.LoadDataSetResponse.LoadDataSetResult
     */
    @WebMethod(operationName = "LoadDataSet", action = "http://frontstep.com/IDOWebService/LoadDataSet")
    @WebResult(name = "LoadDataSetResult", targetNamespace = "http://frontstep.com/IDOWebService")
    @RequestWrapper(localName = "LoadDataSet", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.LoadDataSet")
    @ResponseWrapper(localName = "LoadDataSetResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.LoadDataSetResponse")
    public mypackage.LoadDataSetResponse.LoadDataSetResult loadDataSet(
        @WebParam(name = "strSessionToken", targetNamespace = "http://frontstep.com/IDOWebService")
        String strSessionToken,
        @WebParam(name = "strIDOName", targetNamespace = "http://frontstep.com/IDOWebService")
        String strIDOName,
        @WebParam(name = "strPropertyList", targetNamespace = "http://frontstep.com/IDOWebService")
        String strPropertyList,
        @WebParam(name = "strFilter", targetNamespace = "http://frontstep.com/IDOWebService")
        String strFilter,
        @WebParam(name = "strOrderBy", targetNamespace = "http://frontstep.com/IDOWebService")
        String strOrderBy,
        @WebParam(name = "strPostQueryMethod", targetNamespace = "http://frontstep.com/IDOWebService")
        String strPostQueryMethod,
        @WebParam(name = "iRecordCap", targetNamespace = "http://frontstep.com/IDOWebService")
        int iRecordCap);

    /**
     * 
     * @param strCustomUpdate
     * @param updateDataSet
     * @param strCustomInsert
     * @param refreshAfterSave
     * @param strSessionToken
     * @param strCustomDelete
     * @return
     *     returns mypackage.SaveDataSetResponse.SaveDataSetResult
     */
    @WebMethod(operationName = "SaveDataSet", action = "http://frontstep.com/IDOWebService/SaveDataSet")
    @WebResult(name = "SaveDataSetResult", targetNamespace = "http://frontstep.com/IDOWebService")
    @RequestWrapper(localName = "SaveDataSet", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.SaveDataSet")
    @ResponseWrapper(localName = "SaveDataSetResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.SaveDataSetResponse")
    public mypackage.SaveDataSetResponse.SaveDataSetResult saveDataSet(
        @WebParam(name = "strSessionToken", targetNamespace = "http://frontstep.com/IDOWebService")
        String strSessionToken,
        @WebParam(name = "updateDataSet", targetNamespace = "http://frontstep.com/IDOWebService")
        mypackage.SaveDataSet.UpdateDataSet updateDataSet,
        @WebParam(name = "refreshAfterSave", targetNamespace = "http://frontstep.com/IDOWebService")
        boolean refreshAfterSave,
        @WebParam(name = "strCustomInsert", targetNamespace = "http://frontstep.com/IDOWebService")
        String strCustomInsert,
        @WebParam(name = "strCustomUpdate", targetNamespace = "http://frontstep.com/IDOWebService")
        String strCustomUpdate,
        @WebParam(name = "strCustomDelete", targetNamespace = "http://frontstep.com/IDOWebService")
        String strCustomDelete);

    /**
     * 
     * @param strMethodName
     * @param strMethodParameters
     * @param callMethodResult
     * @param strIDOName
     * @param strSessionToken
     */
    @WebMethod(operationName = "CallMethod", action = "http://frontstep.com/IDOWebService/CallMethod")
    @RequestWrapper(localName = "CallMethod", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.CallMethod")
    @ResponseWrapper(localName = "CallMethodResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.CallMethodResponse")
    public void callMethod(
        @WebParam(name = "strSessionToken", targetNamespace = "http://frontstep.com/IDOWebService")
        String strSessionToken,
        @WebParam(name = "strIDOName", targetNamespace = "http://frontstep.com/IDOWebService")
        String strIDOName,
        @WebParam(name = "strMethodName", targetNamespace = "http://frontstep.com/IDOWebService")
        String strMethodName,
        @WebParam(name = "strMethodParameters", targetNamespace = "http://frontstep.com/IDOWebService", mode = WebParam.Mode.INOUT)
        Holder<String> strMethodParameters,
        @WebParam(name = "CallMethodResult", targetNamespace = "http://frontstep.com/IDOWebService", mode = WebParam.Mode.OUT)
        Holder<Object> callMethodResult);

    /**
     * 
     * @param iRecordCap
     * @param strFilter
     * @param strPostQueryMethod
     * @param strIDOName
     * @param strSessionToken
     * @param strPropertyList
     * @param strOrderBy
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LoadJson", action = "http://frontstep.com/IDOWebService/LoadJson")
    @WebResult(name = "LoadJsonResult", targetNamespace = "http://frontstep.com/IDOWebService")
    @RequestWrapper(localName = "LoadJson", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.LoadJson")
    @ResponseWrapper(localName = "LoadJsonResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.LoadJsonResponse")
    public String loadJson(
        @WebParam(name = "strSessionToken", targetNamespace = "http://frontstep.com/IDOWebService")
        String strSessionToken,
        @WebParam(name = "strIDOName", targetNamespace = "http://frontstep.com/IDOWebService")
        String strIDOName,
        @WebParam(name = "strPropertyList", targetNamespace = "http://frontstep.com/IDOWebService")
        String strPropertyList,
        @WebParam(name = "strFilter", targetNamespace = "http://frontstep.com/IDOWebService")
        String strFilter,
        @WebParam(name = "strOrderBy", targetNamespace = "http://frontstep.com/IDOWebService")
        String strOrderBy,
        @WebParam(name = "strPostQueryMethod", targetNamespace = "http://frontstep.com/IDOWebService")
        String strPostQueryMethod,
        @WebParam(name = "iRecordCap", targetNamespace = "http://frontstep.com/IDOWebService")
        int iRecordCap);

    /**
     * 
     * @param strCustomUpdate
     * @param strCustomInsert
     * @param updateJsonObject
     * @param strSessionToken
     * @param strCustomDelete
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveJson", action = "http://frontstep.com/IDOWebService/SaveJson")
    @WebResult(name = "SaveJsonResult", targetNamespace = "http://frontstep.com/IDOWebService")
    @RequestWrapper(localName = "SaveJson", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.SaveJson")
    @ResponseWrapper(localName = "SaveJsonResponse", targetNamespace = "http://frontstep.com/IDOWebService", className = "mypackage.SaveJsonResponse")
    public String saveJson(
        @WebParam(name = "strSessionToken", targetNamespace = "http://frontstep.com/IDOWebService")
        String strSessionToken,
        @WebParam(name = "updateJsonObject", targetNamespace = "http://frontstep.com/IDOWebService")
        String updateJsonObject,
        @WebParam(name = "strCustomInsert", targetNamespace = "http://frontstep.com/IDOWebService")
        String strCustomInsert,
        @WebParam(name = "strCustomUpdate", targetNamespace = "http://frontstep.com/IDOWebService")
        String strCustomUpdate,
        @WebParam(name = "strCustomDelete", targetNamespace = "http://frontstep.com/IDOWebService")
        String strCustomDelete);

}
