
package mypackage;

import org.springframework.core.io.ClassPathResource;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IDOWebService", targetNamespace = "http://frontstep.com/IDOWebService", wsdlLocation = "file:/C:/Users/15524/Documents/initFrame/src/main/resources/test1.wsdl")
public class IDOWebService
    extends Service
{

    private final static URL IDOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException IDOWEBSERVICE_EXCEPTION;
    private final static QName IDOWEBSERVICE_QNAME = new QName("http://frontstep.com/IDOWebService", "IDOWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            ClassPathResource classPathResource = new ClassPathResource("test1.wsdl");
            url = new URL(classPathResource.getURL().toString());
//            url = new URL("file:/opt/huaxi/G:/HuaXi/src/main/resources/test1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
        IDOWEBSERVICE_WSDL_LOCATION = url;
        IDOWEBSERVICE_EXCEPTION = e;
    }

    public IDOWebService() {
        super(__getWsdlLocation(), IDOWEBSERVICE_QNAME);
    }

    public IDOWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDOWEBSERVICE_QNAME, features);
    }

    public IDOWebService(URL wsdlLocation) {
        super(wsdlLocation, IDOWEBSERVICE_QNAME);
    }

    public IDOWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDOWEBSERVICE_QNAME, features);
    }

    public IDOWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDOWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDOWebServiceSoap
     */
    @WebEndpoint(name = "IDOWebServiceSoap")
    public IDOWebServiceSoap getIDOWebServiceSoap() {
        return super.getPort(new QName("http://frontstep.com/IDOWebService", "IDOWebServiceSoap"), IDOWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDOWebServiceSoap
     */
    @WebEndpoint(name = "IDOWebServiceSoap")
    public IDOWebServiceSoap getIDOWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://frontstep.com/IDOWebService", "IDOWebServiceSoap"), IDOWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns IDOWebServiceSoap
     */
    @WebEndpoint(name = "IDOWebServiceSoap12")
    public IDOWebServiceSoap getIDOWebServiceSoap12() {
        return super.getPort(new QName("http://frontstep.com/IDOWebService", "IDOWebServiceSoap12"), IDOWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDOWebServiceSoap
     */
    @WebEndpoint(name = "IDOWebServiceSoap12")
    public IDOWebServiceSoap getIDOWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://frontstep.com/IDOWebService", "IDOWebServiceSoap12"), IDOWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDOWEBSERVICE_EXCEPTION!= null) {
            throw IDOWEBSERVICE_EXCEPTION;
        }
        return IDOWEBSERVICE_WSDL_LOCATION;
    }

}
